import { create } from "zustand";
import { persist } from "zustand/middleware";
import {
  ANALYSIS_SCENARIO_OPTIONS,
  DEFAULT_DAMPER_CONNECTION_NODE_PAIRS,
  DEFAULT_DAMPER_MATERIALS,
  DEFAULT_OVERALL_TARGETS,
  DEFAULT_STRUCTURAL_RESULT_METRICS,
  getExperimentDesignVariablesForMaterial,
  getOptimizationTargetsByMode,
  MODULE_CATALOG,
  VEHICLE_LIBRARY_OPTIONS,
  WIND_START_TIME_OPTIONS
} from "../api/engineeringOptions";
import type {
  AnalysisScenarioType,
  DamperBaseConfig,
  DamperConnectionNodePair,
  DamperInstanceRegistryEntry,
  DamperMaterialType,
  DoeConfig,
  EngineeringLoadConfig,
  EngineeringModuleId,
  EngineeringProjectConfig,
  GlobalTaskConfig,
  ModuleStatus,
  ModuleStatusKind,
  OptimizationDecisionConfig,
  ResultExtractionConfig,
  ResultExtractionMetricConfig,
  SolverBatchConfig,
  SurrogateLearningConfig,
  SurrogateModelFamily,
  TaskExecutionTarget
} from "../api/types";

type ProjectConfig = EngineeringProjectConfig["projectConfig"];

interface EngineeringConfigState extends EngineeringProjectConfig {
  moduleStatus: ModuleStatus[];
  updateProjectConfig: (patch: Partial<ProjectConfig>) => void;
  updateGlobalTaskConfig: (patch: Partial<GlobalTaskConfig>) => void;
  updateDamperBaseConfig: (patch: Partial<DamperBaseConfig>) => void;
  updateLoadConfig: (patch: Partial<EngineeringLoadConfig>) => void;
  updateDoeConfig: (patch: Partial<DoeConfig>) => void;
  updateSolverBatchConfig: (patch: Partial<SolverBatchConfig>) => void;
  updateResultExtractionConfig: (patch: Partial<ResultExtractionConfig>) => void;
  updateSurrogateLearningConfig: (patch: Partial<SurrogateLearningConfig>) => void;
  updateOptimizationDecisionConfig: (patch: Partial<OptimizationDecisionConfig>) => void;
  validateModule: (moduleId: EngineeringModuleId) => void;
  validateAllModules: () => void;
  getModuleRoute: (moduleId: EngineeringModuleId) => string;
  getEngineeringConfig: () => EngineeringProjectConfig;
}

export const createDamperRegistry = (
  materialType: DamperMaterialType,
  connectionNodePairs: DamperConnectionNodePair[],
  direction: DamperBaseConfig["direction"]
): DamperInstanceRegistryEntry[] => {
  const towerIndexes = { SOUTH: 0, NORTH: 0 };
  return connectionNodePairs
    .filter(pair => (
      Number.isInteger(pair.nodeI)
      && Number.isInteger(pair.nodeJ)
      && pair.nodeI > 0
      && pair.nodeJ > 0
      && pair.nodeI !== pair.nodeJ
    ))
    .map((pair, index) => {
      towerIndexes[pair.tower] += 1;
      const towerCode = pair.tower === "SOUTH" ? "S" : "N";
      return {
        damperId: `${towerCode}D${String(towerIndexes[pair.tower]).padStart(2, "0")}`,
        materialType,
        placementLabel: pair.label || `${pair.tower === "SOUTH" ? "南塔" : "北塔"}节点 ${pair.nodeI}-${pair.nodeJ}`,
        elementType: "USER300" as const,
        elementId: 9301 + index,
        nodeI: pair.nodeI,
        nodeJ: pair.nodeJ,
        direction,
        source: "USER_DEFINED" as const
      };
    });
};

const hasValidDamperConnectionNodes = (pairs: DamperConnectionNodePair[]) => (
  pairs.length > 0 && pairs.every(pair => (
    Number.isInteger(pair.nodeI)
    && Number.isInteger(pair.nodeJ)
    && pair.nodeI > 0
    && pair.nodeJ > 0
    && pair.nodeI !== pair.nodeJ
  ))
);

const createAutoDamperMetrics = (
  registry: DamperInstanceRegistryEntry[]
): ResultExtractionMetricConfig[] =>
  registry.flatMap(item => [
    {
      id: `${item.damperId}_force`,
      name: `${item.placementLabel} 阻尼器出力`,
      objectType: "DAMPER",
      objectId: `USER300:${item.elementId}`,
      component: "LOCAL_AXIAL",
      responseType: "DAMPER_FORCE",
      statistic: "ABS_PEAK",
      enabled: true,
      autoGenerated: true,
      sourceDamperId: item.damperId,
      sourceDescription: `自动来自 ${item.damperId} 单元 ${item.elementId}`
    },
    {
      id: `${item.damperId}_stroke`,
      name: `${item.placementLabel} 阻尼器行程`,
      objectType: "DAMPER",
      objectId: `${item.nodeI}-${item.nodeJ}`,
      component: item.direction,
      responseType: "DAMPER_STROKE",
      statistic: "ABS_PEAK",
      enabled: true,
      autoGenerated: true,
      sourceDamperId: item.damperId,
      sourceDescription: `自动来自节点 ${item.nodeI}/${item.nodeJ} 相对位移`
    },
    {
      id: `${item.damperId}_energy`,
      name: `${item.placementLabel} 耗能`,
      objectType: "DAMPER",
      objectId: `USER300:${item.elementId}`,
      component: "LOCAL_AXIAL",
      responseType: "ENERGY",
      statistic: "CUMULATIVE",
      enabled: true,
      autoGenerated: true,
      sourceDamperId: item.damperId,
      sourceDescription: "自动由阻尼器出力-行程时程积分"
    }
  ]);

const defaultConnectionNodePairs = DEFAULT_DAMPER_CONNECTION_NODE_PAIRS.map(pair => ({ ...pair }));
const defaultRegistry = createDamperRegistry("VISCOUS", defaultConnectionNodePairs, "LOCAL_AXIAL");
const EARTHQUAKE_SURROGATE_MODELS: SurrogateModelFamily[] = [
  "GPR",
  "KRIGING",
  "RBF",
  "RESPONSE_SURFACE",
  "SVR",
  "PCE",
  "MARS"
];

const defaultLoadConfig: EngineeringLoadConfig = {
  earthquake: {
    sourceMode: "GENERATED",
    configured: false,
    validated: false,
    fileInput: {
      fileName: "请选择地震波文件",
      artifactId: "",
      sourceSha256: "",
      availableColumns: [],
      timeColumn: "",
      valueColumn: "",
      consistentExcitation: false,
      fileType: "CSV",
      timeStepS: 0.02,
      durationS: 40,
      unit: "m/s2",
      direction: "UX",
      nodeMapping: "base_nodes"
    },
    codeGeneration: {
      startTime: "2026-07-01T00:00:00+08:00",
      durationS: 40,
      timeStepS: 0.02,
      code: "JTG/T 2231-01",
      intensity: "VIII",
      siteClass: "II",
      designGroup: "第一组",
      dampingRatio: 0.05,
      pgaScaleFactor: 1,
      spectrumMatch: true,
      directions: ["LONGITUDINAL"]
    }
  },
  wind: {
    sourceMode: "GENERATED",
    configured: false,
    validated: false,
    fileInput: {
      fileName: "请选择风荷载时程文件",
      artifactId: "",
      sourceSha256: "",
      availableColumns: [],
      timeColumn: "",
      valueColumn: "",
      consistentExcitation: false,
      fileType: "CSV",
      timeStepS: 1,
      durationS: 600,
      unit: "kN",
      direction: "UZ",
      nodeMapping: "girder_vertical_nodes"
    },
    generated: {
      meanWindSpeed: 10,
      attackAngleDeg: 0,
      turbulenceIntensity: 0.14,
      spectrumModel: "Davenport",
      spatialCorrelation: 0.75,
      components: ["主梁升力"],
      targets: ["主梁"],
      startTime: WIND_START_TIME_OPTIONS[0]?.id ?? "2026-07-01T00:00:00+08:00",
      durationS: 600,
      timeStepS: 1
    }
  },
  traffic: {
    sourceMode: "GENERATED",
    configured: false,
    validated: false,
    fileInput: {
      fileName: "请选择车辆荷载时程文件",
      artifactId: "",
      sourceSha256: "",
      availableColumns: [],
      timeColumn: "",
      valueColumn: "",
      consistentExcitation: false,
      fileType: "CSV",
      timeStepS: 1,
      durationS: 86400,
      unit: "kN",
      direction: "UZ",
      nodeMapping: "lane_to_girder_nodes"
    },
    generated: {
      laneCount: 2,
      vehicleLibraryId: VEHICLE_LIBRARY_OPTIONS[0]?.id ?? "vehicle_library_wim_2021_01",
      vehicleTypes: ["小客车", "中型货车", "重型货车"],
      speedDistribution: "正态分布",
      headwayDistribution: "负指数分布",
      trafficScale: 1,
      heavyVehicleScale: 1,
      startTime: "2026-07-01T00:00:00+08:00",
      durationS: 86400,
      timeStepS: 1,
      seed: 20260702,
      laneMapping: "主梁双向加载"
    }
  }
};

const defaultDamperBaseConfig: DamperBaseConfig = {
  enabled: true,
  materialType: "VISCOUS",
  southTowerCount: 2,
  northTowerCount: 2,
  direction: "LOCAL_AXIAL",
  connectionNodePairs: defaultConnectionNodePairs,
  placementValidated: true,
  damperInstanceRegistry: defaultRegistry
};

const defaultDoeConfig: DoeConfig = {
  method: "LHS",
  variables: getExperimentDesignVariablesForMaterial("VISCOUS"),
  sampleCount: 10,
  seed: 20260702,
  includeCorners: true,
  includeCenter: true,
  validated: false
};

const defaultSolverBatchConfig: SolverBatchConfig = {
  solver: "ANSYS",
  analysisType: "TRANSIENT_DYNAMIC",
  batchMode: "PARALLEL",
  processCount: 4,
  coresPerProcess: 1,
  caseTimeoutS: 7200,
  retryCount: 1,
  outputDirectory: "runs/stbridge_doe",
  keepIntermediateFiles: true,
  autoCleanTemporaryFiles: false,
  completionAction: "AUTO_POSTPROCESS",
  validated: false
};

const defaultSurrogateConfig: SurrogateLearningConfig = {
  datasetSourceMode: "DOE_DATASET",
  datasetId: "doe_latest_raw_response",
  modelFamilies: EARTHQUAKE_SURROGATE_MODELS,
  inputVariableIds: ["dampingCoefficient", "velocityExponent"],
  outputResponseIds: ["beamEndDisplacement", "towerBaseShear", "towerBaseMoment", "beamEndCumulativeDisplacement"],
  trainRatio: 0.8,
  validationMethod: "K_FOLD",
  folds: 5,
  metrics: ["R2", "RMSE", "MAE"],
  activeLearningEnabled: false,
  activeLearningStrategy: "MAX_UNCERTAINTY",
  maxAdditionalSamples: 12,
  convergenceTolerance: 0.03,
  validated: false
};

const defaultOptimizationConfig: OptimizationDecisionConfig = {
  algorithm: "NSGA2",
  objectiveMode: "OVERALL",
  designVariableIds: ["dampingCoefficient", "velocityExponent"],
  objectives: getOptimizationTargetsByMode("OVERALL").map(name => ({ name, direction: "MIN" })),
  constraints: [
    { targetId: "beamEndDisplacement", name: "梁端位移不超过无控状态", operator: "<=", value: 0.12, unit: "m", source: "UNCONTROLLED" },
    { targetId: "towerBaseShear", name: "塔底剪力不超过无控状态", operator: "<=", value: 68000, unit: "kN", source: "UNCONTROLLED" },
    { targetId: "towerBaseMoment", name: "塔底弯矩不超过无控状态", operator: "<=", value: 3200000, unit: "kN*m", source: "UNCONTROLLED" },
    { targetId: "beamEndCumulativeDisplacement", name: "梁端累计位移不超过无控状态", operator: "<=", value: 28, unit: "m", source: "UNCONTROLLED" }
  ],
  economics: {
    damperUnitCost: DEFAULT_DAMPER_MATERIALS.VISCOUS.unitCost,
    totalCostLimit: 1200000,
    efficiencyMetric: "单位造价减振效率"
  },
  decisionMethods: ["TOPSIS", "ENTROPY_WEIGHT"],
  validated: false
};

const createDefaultConfig = (): EngineeringProjectConfig => ({
  projectConfig: {
    projectName: "MOMO 桥梁阻尼器优化分析",
    modelFile: {
      fileName: "STbridge.txt",
      filePath: "bridge_models/STbridge.txt",
      format: "APDL",
      parseStatus: "PARSED",
      parsedAt: new Date().toISOString(),
      summary: {
        nodeCount: 642,
        elementCount: 1186,
        detectedDamperCount: defaultRegistry.length
      }
    }
  },
  globalTaskConfig: {
    solver: "ANSYS",
    scenario: "EARTHQUAKE",
    executionTarget: "OPTIMIZATION_DECISION"
  },
  damperBaseConfig: defaultDamperBaseConfig,
  loadConfig: defaultLoadConfig,
  doeConfig: defaultDoeConfig,
  solverBatchConfig: defaultSolverBatchConfig,
  resultExtractionConfig: {
    structuralMetrics: DEFAULT_STRUCTURAL_RESULT_METRICS,
    autoDamperMetrics: createAutoDamperMetrics(defaultRegistry),
    exportRawData: true,
    validated: false
  },
  surrogateLearningConfig: defaultSurrogateConfig,
  optimizationDecisionConfig: defaultOptimizationConfig
});

const getRequiredModules = (
  scenario: AnalysisScenarioType,
  target: TaskExecutionTarget
): EngineeringModuleId[] => {
  const required = new Set<EngineeringModuleId>(["DAMPER_BASE", "DOE"]);
  if (target !== "DESIGN_SAMPLES") required.add("LOADS");
  if (["BATCH_SOLVE", "RESULT_EXTRACTION", "SURROGATE_TRAINING", "OPTIMIZATION_DECISION"].includes(target)) {
    required.add("SOLVER_BATCH");
    required.add("RESULT_EXTRACTION");
  }
  if (target === "SURROGATE_TRAINING" || target === "OPTIMIZATION_DECISION") {
    required.add("SURROGATE_LEARNING");
  }
  if (target === "OPTIMIZATION_DECISION") required.add("OPTIMIZATION_DECISION");
  if (scenario && target === "COMMAND_STREAM") required.add("LOADS");
  return Array.from(required);
};

const loadRouteForScenario = (scenario: AnalysisScenarioType, loadConfig: EngineeringLoadConfig) => {
  if (scenario === "EARTHQUAKE") return "/loads?tab=earthquake";
  if (scenario === "WIND") return "/loads?tab=wind";
  if (scenario === "TRAFFIC") return "/loads?tab=traffic";
  if (!loadConfig.wind.configured) return "/loads?tab=wind";
  return "/loads?tab=traffic";
};

const evaluateLoadStatus = (
  scenario: AnalysisScenarioType,
  loadConfig: EngineeringLoadConfig
): { status: ModuleStatusKind; message: string; route: string } => {
  if (scenario === "EARTHQUAKE") {
    if (!loadConfig.earthquake.configured) {
      return { status: "UNCONFIGURED", message: "地震荷载未配置，点击前往配置", route: "/loads?tab=earthquake" };
    }
    return {
      status: loadConfig.earthquake.validated ? "VALIDATED" : "CONFIGURED",
      message: "地震荷载已配置",
      route: "/loads?tab=earthquake"
    };
  }
  if (scenario === "WIND") {
    if (!loadConfig.wind.configured) {
      return { status: "UNCONFIGURED", message: "风荷载未配置，点击前往配置", route: "/loads?tab=wind" };
    }
    return {
      status: loadConfig.wind.validated ? "VALIDATED" : "CONFIGURED",
      message: "风荷载已配置",
      route: "/loads?tab=wind"
    };
  }
  if (scenario === "TRAFFIC") {
    if (!loadConfig.traffic.configured) {
      return { status: "UNCONFIGURED", message: "车流荷载未配置，点击前往配置", route: "/loads?tab=traffic" };
    }
    return {
      status: loadConfig.traffic.validated ? "VALIDATED" : "CONFIGURED",
      message: "车流荷载已配置",
      route: "/loads?tab=traffic"
    };
  }

  if (!loadConfig.wind.configured && !loadConfig.traffic.configured) {
    return { status: "UNCONFIGURED", message: "风荷载与车流荷载均未配置", route: "/loads?tab=wind" };
  }
  if (!loadConfig.wind.configured) {
    return { status: "INCOMPLETE", message: "风-车组合缺少风荷载配置", route: "/loads?tab=wind" };
  }
  if (!loadConfig.traffic.configured) {
    return { status: "INCOMPLETE", message: "风-车组合缺少车流荷载配置", route: "/loads?tab=traffic" };
  }
  return {
    status: loadConfig.wind.validated && loadConfig.traffic.validated ? "VALIDATED" : "CONFIGURED",
    message: "风荷载和车流荷载已配置",
    route: loadRouteForScenario(scenario, loadConfig)
  };
};

const buildModuleStatus = (config: EngineeringProjectConfig): ModuleStatus[] => {
  const requiredModules = getRequiredModules(
    config.globalTaskConfig.scenario,
    config.globalTaskConfig.executionTarget
  );
  const requiredSet = new Set(requiredModules);
  const loadStatus = evaluateLoadStatus(config.globalTaskConfig.scenario, config.loadConfig);

  const moduleEvaluators: Record<EngineeringModuleId, () => Pick<ModuleStatus, "status" | "message" | "route">> = {
    DOE: () => ({
      status: config.doeConfig.variables.some(item => item.enabled) && config.doeConfig.sampleCount > 0
        ? config.doeConfig.validated ? "VALIDATED" : "CONFIGURED"
        : "UNCONFIGURED",
      message: config.doeConfig.variables.some(item => item.enabled)
        ? `已选择 ${config.doeConfig.variables.filter(item => item.enabled).length} 个 DOE 变量`
        : "未选择 DOE 设计变量",
      route: "/experiment-design"
    }),
    DAMPER_BASE: () => {
      const hasValidNodes = hasValidDamperConnectionNodes(config.damperBaseConfig.connectionNodePairs);
      const hasRegistry = config.damperBaseConfig.damperInstanceRegistry.length > 0;
      if (config.projectConfig.modelFile.parseStatus !== "PARSED") {
        return { status: "INCOMPLETE", message: "模型文件尚未解析，无法生成阻尼器注册表", route: "/damper-base" };
      }
      if (!hasRegistry) {
        return { status: "UNCONFIGURED", message: "未生成阻尼器实例注册表", route: "/damper-base" };
      }
      if (!hasValidNodes) {
        return { status: "INCOMPLETE", message: "自定义连接节点必须为不同的正整数节点", route: "/damper-base" };
      }
      return {
        status: config.damperBaseConfig.placementValidated ? "VALIDATED" : "CONFIGURED",
        message: `已按自定义节点注册 ${config.damperBaseConfig.damperInstanceRegistry.length} 个 USER300 阻尼器`,
        route: "/damper-base"
      };
    },
    LOADS: () => loadStatus,
    SOLVER_BATCH: () => ({
      status: config.solverBatchConfig.processCount > 0 && config.solverBatchConfig.coresPerProcess > 0
        ? config.solverBatchConfig.validated ? "VALIDATED" : "CONFIGURED"
        : "INCOMPLETE",
      message: `${config.solverBatchConfig.batchMode === "PARALLEL" ? "并行" : "串行"}：${config.solverBatchConfig.processCount} 进程，每进程 ${config.solverBatchConfig.coresPerProcess} 核`,
      route: "/solver"
    }),
    RESULT_EXTRACTION: () => {
      const enabledStructural = config.resultExtractionConfig.structuralMetrics.filter(item => item.enabled).length;
      const enabledDamper = config.resultExtractionConfig.autoDamperMetrics.filter(item => item.enabled).length;
      if (enabledStructural === 0 && enabledDamper === 0) {
        return { status: "UNCONFIGURED", message: "尚未启用任何结果提取指标", route: "/results" };
      }
      return {
        status: config.resultExtractionConfig.validated ? "VALIDATED" : "CONFIGURED",
        message: `结构指标 ${enabledStructural} 项，阻尼器自动指标 ${enabledDamper} 项`,
        route: "/results"
      };
    },
    SURROGATE_LEARNING: () => ({
      status: config.surrogateLearningConfig.modelFamilies.length > 0 && config.surrogateLearningConfig.outputResponseIds.length > 0
        ? config.surrogateLearningConfig.validated ? "VALIDATED" : "CONFIGURED"
        : "UNCONFIGURED",
      message: `代理模型：${config.surrogateLearningConfig.modelFamilies.join(", ")}`,
      route: "/surrogate"
    }),
    OPTIMIZATION_DECISION: () => ({
      status: config.optimizationDecisionConfig.objectives.length > 0
        ? config.optimizationDecisionConfig.validated ? "VALIDATED" : "CONFIGURED"
        : "UNCONFIGURED",
      message: `目标 ${config.optimizationDecisionConfig.objectives.length} 项，决策方法 ${config.optimizationDecisionConfig.decisionMethods.length} 项`,
      route: "/optimization"
    })
  };

  return MODULE_CATALOG.map(item => {
    const evaluated = moduleEvaluators[item.moduleId]();
    return {
      ...item,
      ...evaluated,
      required: requiredSet.has(item.moduleId)
    };
  });
};

const regenerateDamperDerivedState = (
  config: EngineeringProjectConfig,
  patch: Partial<DamperBaseConfig>
): EngineeringProjectConfig => {
  const nextDamper = { ...config.damperBaseConfig, ...patch };
  const connectionNodePairs = nextDamper.connectionNodePairs;
  const registry = createDamperRegistry(
    nextDamper.materialType,
    connectionNodePairs,
    nextDamper.direction
  );
  const nextConfig: EngineeringProjectConfig = {
    ...config,
    damperBaseConfig: {
      ...nextDamper,
      southTowerCount: connectionNodePairs.filter(pair => pair.tower === "SOUTH").length,
      northTowerCount: connectionNodePairs.filter(pair => pair.tower === "NORTH").length,
      damperInstanceRegistry: registry,
      placementValidated: patch.placementValidated ?? false
    },
    doeConfig: {
      ...config.doeConfig,
      variables: getExperimentDesignVariablesForMaterial(nextDamper.materialType),
      validated: false
    },
    resultExtractionConfig: {
      ...config.resultExtractionConfig,
      autoDamperMetrics: createAutoDamperMetrics(registry),
      validated: false
    }
  };
  return nextConfig;
};

const withStatus = (config: EngineeringProjectConfig) => ({
  ...config,
  moduleStatus: buildModuleStatus(config)
});

const engineeringConfigFromState = (state: EngineeringProjectConfig): EngineeringProjectConfig => ({
  projectConfig: state.projectConfig,
  globalTaskConfig: state.globalTaskConfig,
  damperBaseConfig: state.damperBaseConfig,
  loadConfig: state.loadConfig,
  doeConfig: state.doeConfig,
  solverBatchConfig: state.solverBatchConfig,
  resultExtractionConfig: state.resultExtractionConfig,
  surrogateLearningConfig: state.surrogateLearningConfig,
  optimizationDecisionConfig: state.optimizationDecisionConfig
});

const normalizeRehydratedState = (state: EngineeringConfigState) => {
  const connectionNodePairs = state.damperBaseConfig.connectionNodePairs?.length
    ? state.damperBaseConfig.connectionNodePairs
    : defaultConnectionNodePairs;
  state.damperBaseConfig = {
    ...state.damperBaseConfig,
    connectionNodePairs,
    southTowerCount: connectionNodePairs.filter(pair => pair.tower === "SOUTH").length,
    northTowerCount: connectionNodePairs.filter(pair => pair.tower === "NORTH").length,
    damperInstanceRegistry: createDamperRegistry(
      state.damperBaseConfig.materialType,
      connectionNodePairs,
      state.damperBaseConfig.direction
    )
  };
  const normalizeMetric = (metric: ResultExtractionMetricConfig) => {
    const defaultMetric = DEFAULT_STRUCTURAL_RESULT_METRICS.find(item => item.id === metric.id);
    if (!defaultMetric) return metric;
    if (
      metric.id === "metric_beam_end_ux_cumulative" ||
      metric.id === "metric_tower_base_shear" ||
      metric.id === "metric_tower_base_moment"
    ) {
      return {
        ...metric,
        objectId: defaultMetric.objectId,
        statistic: defaultMetric.statistic,
        sourceDescription: defaultMetric.sourceDescription
      };
    }
    return metric;
  };

  const structuralMetrics = state.resultExtractionConfig.structuralMetrics.map(normalizeMetric);
  if (!structuralMetrics.some(metric => metric.id === "metric_beam_end_ux_cumulative")) {
    const cumulativeMetric = DEFAULT_STRUCTURAL_RESULT_METRICS.find(
      metric => metric.id === "metric_beam_end_ux_cumulative"
    );
    if (cumulativeMetric) {
      const insertIndex = structuralMetrics.findIndex(metric => metric.id === "metric_beam_end_ux_peak");
      structuralMetrics.splice(insertIndex >= 0 ? insertIndex + 1 : structuralMetrics.length, 0, cumulativeMetric);
    }
  }

  state.loadConfig = {
    ...state.loadConfig,
    earthquake: {
      ...state.loadConfig.earthquake,
      fileInput: {
        ...defaultLoadConfig.earthquake.fileInput,
        ...state.loadConfig.earthquake.fileInput
      },
      codeGeneration: {
        ...defaultLoadConfig.earthquake.codeGeneration,
        ...state.loadConfig.earthquake.codeGeneration
      }
    },
    wind: {
      ...state.loadConfig.wind,
      fileInput: {
        ...defaultLoadConfig.wind.fileInput,
        ...state.loadConfig.wind.fileInput
      },
      generated: {
        ...defaultLoadConfig.wind.generated,
        ...state.loadConfig.wind.generated
      }
    },
    traffic: {
      ...state.loadConfig.traffic,
      fileInput: {
        ...defaultLoadConfig.traffic.fileInput,
        ...state.loadConfig.traffic.fileInput
      },
      generated: {
        ...defaultLoadConfig.traffic.generated,
        ...state.loadConfig.traffic.generated
      }
    }
  };
  state.doeConfig = {
    ...state.doeConfig,
    sampleCount: state.doeConfig.sampleCount === 24 ? defaultDoeConfig.sampleCount : state.doeConfig.sampleCount,
    includeCorners: true,
    includeCenter: true,
    variables: state.doeConfig.variables.map(variable => {
      const defaultVariable = defaultDoeConfig.variables.find(item => item.id === variable.id);
      if (!defaultVariable) return variable;
      if (
        variable.id === "dampingCoefficient" &&
        variable.min === 600 &&
        variable.max === 2400
      ) {
        return { ...variable, min: defaultVariable.min, max: defaultVariable.max };
      }
      if (
        variable.id === "velocityExponent" &&
        variable.min === 0.2 &&
        variable.max === 0.8
      ) {
        return { ...variable, min: defaultVariable.min, max: defaultVariable.max };
      }
      return variable;
    })
  };
  state.solverBatchConfig = {
    ...state.solverBatchConfig,
    processCount: state.solverBatchConfig.processCount || defaultSolverBatchConfig.processCount,
    coresPerProcess: state.solverBatchConfig.coresPerProcess === 2
      ? defaultSolverBatchConfig.coresPerProcess
      : state.solverBatchConfig.coresPerProcess
  };
  state.surrogateLearningConfig = {
    ...state.surrogateLearningConfig,
    outputResponseIds: [...DEFAULT_OVERALL_TARGETS],
    modelFamilies: state.surrogateLearningConfig.modelFamilies
      .map(model => String(model) === "RSM" ? "RESPONSE_SURFACE" : model)
      .filter((model, index, models): model is SurrogateModelFamily => (
        EARTHQUAKE_SURROGATE_MODELS.includes(model as SurrogateModelFamily) &&
        models.indexOf(model) === index
      ))
  };
  if (state.surrogateLearningConfig.modelFamilies.length === 0) {
    state.surrogateLearningConfig.modelFamilies = EARTHQUAKE_SURROGATE_MODELS;
  }
  if (state.optimizationDecisionConfig.objectiveMode !== "CUSTOM") {
    const objectives = getOptimizationTargetsByMode(state.optimizationDecisionConfig.objectiveMode)
      .map(name => ({ name, direction: "MIN" as const }));
    state.optimizationDecisionConfig = {
      ...state.optimizationDecisionConfig,
      objectives,
      constraints: state.optimizationDecisionConfig.constraints.filter(constraint => (
        objectives.some(objective => objective.name === constraint.targetId)
      ))
    };
  }
  state.resultExtractionConfig = {
    ...state.resultExtractionConfig,
    structuralMetrics
  };
  state.moduleStatus = buildModuleStatus(state);
};

const initialConfig = createDefaultConfig();

export const useEngineeringConfigStore = create<EngineeringConfigState>()(
  persist(
    (set, get) => ({
      ...initialConfig,
      moduleStatus: buildModuleStatus(initialConfig),

      updateProjectConfig: patch => set(state => {
        const next = {
          ...state,
          projectConfig: {
            ...state.projectConfig,
            ...patch,
            modelFile: patch.modelFile
              ? { ...state.projectConfig.modelFile, ...patch.modelFile }
              : state.projectConfig.modelFile
          }
        };
        return withStatus(next);
      }),

      updateGlobalTaskConfig: patch => set(state => {
        const next = {
          ...state,
          globalTaskConfig: { ...state.globalTaskConfig, ...patch },
          solverBatchConfig: patch.solver
            ? { ...state.solverBatchConfig, solver: patch.solver, validated: false }
            : state.solverBatchConfig
        };
        return withStatus(next);
      }),

      updateDamperBaseConfig: patch => set(state => withStatus(regenerateDamperDerivedState(state, patch))),

      updateLoadConfig: patch => set(state => {
        const next = { ...state, loadConfig: { ...state.loadConfig, ...patch } };
        return withStatus(next);
      }),

      updateDoeConfig: patch => set(state => {
        const next = { ...state, doeConfig: { ...state.doeConfig, ...patch } };
        return withStatus(next);
      }),

      updateSolverBatchConfig: patch => set(state => {
        const next = { ...state, solverBatchConfig: { ...state.solverBatchConfig, ...patch } };
        return withStatus(next);
      }),

      updateResultExtractionConfig: patch => set(state => {
        const next = { ...state, resultExtractionConfig: { ...state.resultExtractionConfig, ...patch } };
        return withStatus(next);
      }),

      updateSurrogateLearningConfig: patch => set(state => {
        const next = { ...state, surrogateLearningConfig: { ...state.surrogateLearningConfig, ...patch } };
        return withStatus(next);
      }),

      updateOptimizationDecisionConfig: patch => set(state => {
        const next = { ...state, optimizationDecisionConfig: { ...state.optimizationDecisionConfig, ...patch } };
        return withStatus(next);
      }),

      validateModule: moduleId => set(state => {
        const next: EngineeringProjectConfig = { ...state };
        if (moduleId === "DOE") next.doeConfig = { ...state.doeConfig, validated: true };
        if (moduleId === "DAMPER_BASE") {
          next.damperBaseConfig = {
            ...state.damperBaseConfig,
            placementValidated: hasValidDamperConnectionNodes(state.damperBaseConfig.connectionNodePairs)
          };
        }
        if (moduleId === "LOADS") {
          const scenario = state.globalTaskConfig.scenario;
          next.loadConfig = {
            ...state.loadConfig,
            earthquake: scenario === "EARTHQUAKE"
              ? { ...state.loadConfig.earthquake, configured: true, validated: true }
              : state.loadConfig.earthquake,
            wind: scenario === "WIND" || scenario === "WIND_TRAFFIC"
              ? { ...state.loadConfig.wind, configured: true, validated: true }
              : state.loadConfig.wind,
            traffic: scenario === "TRAFFIC" || scenario === "WIND_TRAFFIC"
              ? { ...state.loadConfig.traffic, configured: true, validated: true }
              : state.loadConfig.traffic
          };
        }
        if (moduleId === "SOLVER_BATCH") next.solverBatchConfig = { ...state.solverBatchConfig, validated: true };
        if (moduleId === "RESULT_EXTRACTION") next.resultExtractionConfig = { ...state.resultExtractionConfig, validated: true };
        if (moduleId === "SURROGATE_LEARNING") next.surrogateLearningConfig = { ...state.surrogateLearningConfig, validated: true };
        if (moduleId === "OPTIMIZATION_DECISION") next.optimizationDecisionConfig = { ...state.optimizationDecisionConfig, validated: true };
        return withStatus(next);
      }),

      validateAllModules: () => {
        const current = get();
        getRequiredModules(current.globalTaskConfig.scenario, current.globalTaskConfig.executionTarget)
          .forEach(moduleId => get().validateModule(moduleId));
      },

      getModuleRoute: moduleId => get().moduleStatus.find(item => item.moduleId === moduleId)?.route ?? "/",
      getEngineeringConfig: () => engineeringConfigFromState(get())
    }),
    {
      name: "momo_engineering_config_v1",
      partialize: state => engineeringConfigFromState(state),
      onRehydrateStorage: () => state => {
        if (!state) return;
        normalizeRehydratedState(state);
      }
    }
  )
);

export const getScenarioLabel = (scenario: AnalysisScenarioType) =>
  ANALYSIS_SCENARIO_OPTIONS.find(item => item.id === scenario)?.label ?? scenario;
