"""Optimization and decision utilities."""

from .constraints import Constraint, check_constraints, constraint_violation, feasibility_first_compare
from .config_runner import (
    BaselineOptimizationWorkflowResult,
    SolverParityWorkflowResult,
    preflight_config,
    run_sampled_doe_optimization_config,
    run_solver_acceptance_case_config,
    run_solver_parity_workflow_config,
    run_undamped_baseline_config,
    run_undamped_baseline_optimization_workflow_config,
)
from .damper_plan import OptimizedDamperPlan, realize_optimized_damper_plan
from .decision import (
    ScenarioDecisionResult,
    TopsisResult,
    VerifiedSolverDecisionResult,
    combine_scenario_objectives,
    entropy_topsis,
    entropy_weights,
    scenario_entropy_topsis,
    topsis,
    topsis_details,
    topsis_verified_solver_outputs,
)
from .decision_explainability import (
    evaluate_decision_robustness,
    explain_topsis_decision,
    perturb_design,
)
from .doe_pipeline import (
    DamperDOEObjectiveSpec,
    DamperDOEOptimizationResult,
    optimize_from_damper_doe_batch,
    optimize_from_sampled_damper_doe,
)
from .fem_review import (
    FEMObjectiveCheck,
    FEMReviewRecord,
    FEMValidationRecord,
    compare_fem_objectives,
    damper_params_from_candidate,
    damper_params_from_design,
    run_fem_review,
    run_validation_designs,
)
from .nsga2 import feasibility_first_dominates, nsga2_pareto_search, random_pareto_search
from .objectives import (
    OBJECTIVE_REGISTRY,
    cumulative_absolute_response,
    cumulative_displacement_objective,
    objective_value,
    objective_vector,
    register_objective,
)
from .pipeline import FEMValidationReport, OptimizationPipelineResult, SurrogateObjectiveSpec, optimize_from_result_stores
from .pymoo_adapter import (
    PRODUCTION_NSGA2_OPTIMIZER,
    PymooOptimizationResult,
    optimize_with_production_nsga2,
    optimize_with_pymoo_nsga2,
)
from .review import FEMReviewCandidate, pareto_knee_index, robust_pareto_index, select_fem_review_candidates
from .robustness import robustness_score, scenario_weight_sensitivity, topsis_weight_sensitivity
from .workflow import (
    ScenarioSurrogate,
    SurrogateOptimizationResult,
    decision_weights_for_surrogates,
    evaluate_scenario_surrogates,
    optimize_with_surrogates,
    scenario_decision_for_surrogates,
)

__all__ = [
    "Constraint",
    "DamperDOEObjectiveSpec",
    "DamperDOEOptimizationResult",
    "BaselineOptimizationWorkflowResult",
    "SolverParityWorkflowResult",
    "FEMObjectiveCheck",
    "FEMReviewCandidate",
    "FEMReviewRecord",
    "FEMValidationRecord",
    "FEMValidationReport",
    "OptimizationPipelineResult",
    "OptimizedDamperPlan",
    "PymooOptimizationResult",
    "ScenarioSurrogate",
    "ScenarioDecisionResult",
    "SurrogateObjectiveSpec",
    "SurrogateOptimizationResult",
    "TopsisResult",
    "VerifiedSolverDecisionResult",
    "OBJECTIVE_REGISTRY",
    "PRODUCTION_NSGA2_OPTIMIZER",
    "check_constraints",
    "compare_fem_objectives",
    "combine_scenario_objectives",
    "constraint_violation",
    "entropy_topsis",
    "entropy_weights",
    "feasibility_first_compare",
    "feasibility_first_dominates",
    "decision_weights_for_surrogates",
    "evaluate_scenario_surrogates",
    "evaluate_decision_robustness",
    "explain_topsis_decision",
    "cumulative_absolute_response",
    "cumulative_displacement_objective",
    "objective_value",
    "objective_vector",
    "optimize_from_result_stores",
    "optimize_from_damper_doe_batch",
    "optimize_from_sampled_damper_doe",
    "optimize_with_surrogates",
    "optimize_with_pymoo_nsga2",
    "optimize_with_production_nsga2",
    "pareto_knee_index",
    "perturb_design",
    "preflight_config",
    "nsga2_pareto_search",
    "random_pareto_search",
    "realize_optimized_damper_plan",
    "register_objective",
    "robust_pareto_index",
    "robustness_score",
    "scenario_weight_sensitivity",
    "run_sampled_doe_optimization_config",
    "run_solver_acceptance_case_config",
    "run_solver_parity_workflow_config",
    "run_undamped_baseline_config",
    "run_undamped_baseline_optimization_workflow_config",
    "damper_params_from_candidate",
    "damper_params_from_design",
    "run_fem_review",
    "run_validation_designs",
    "select_fem_review_candidates",
    "scenario_entropy_topsis",
    "scenario_decision_for_surrogates",
    "topsis",
    "topsis_details",
    "topsis_verified_solver_outputs",
    "topsis_weight_sensitivity",
]
