"""工程工作流共享的资源边界。"""

DOE_INITIAL_DEFAULT = 15
DOE_INITIAL_MIN = 5
DOE_INITIAL_MAX = 24
DOE_ACTIVE_LEARNING_BATCH = 2
DOE_ACTIVE_LEARNING_MAX_ITERATIONS = 2
DOE_ACTIVE_LEARNING_MAX_ADDITIONAL = (
    DOE_ACTIVE_LEARNING_BATCH * DOE_ACTIVE_LEARNING_MAX_ITERATIONS
)
# 无控基线和独立最终复核各占一个设计级真实求解预算。
DOE_FIXED_REAL_SOLVE_OVERHEAD = 2
