import { describe, expect, it } from "vitest";
import type { ResultExtractionMetricConfig } from "./types";
import {
  DEFAULT_OPERATION_TARGETS,
  DEFAULT_OVERALL_TARGETS,
  DEFAULT_SEISMIC_TARGETS,
  DEFAULT_SURROGATE_TARGET_METRIC_IDS,
  getSurrogateResponseMetricOptions,
  getOptimizationTargetsByMode
} from "./engineeringOptions";

describe("optimization objective contracts", () => {
  it("uses the three structural earthquake responses for seismic optimization", () => {
    expect(getOptimizationTargetsByMode("SEISMIC")).toEqual(DEFAULT_SEISMIC_TARGETS);
    expect(DEFAULT_SEISMIC_TARGETS).toEqual([
      "beamEndDisplacement",
      "towerBaseShear",
      "towerBaseMoment"
    ]);
  });

  it("uses only cumulative girder-end displacement for operation optimization", () => {
    expect(getOptimizationTargetsByMode("OPERATION")).toEqual([
      "beamEndCumulativeDisplacement"
    ]);
    expect(DEFAULT_OPERATION_TARGETS).not.toContain("damperCost");
  });

  it("uses all four structural responses for overall optimization", () => {
    expect(getOptimizationTargetsByMode("OVERALL")).toEqual(DEFAULT_OVERALL_TARGETS);
    expect(DEFAULT_OVERALL_TARGETS).toEqual([
      ...DEFAULT_SEISMIC_TARGETS,
      ...DEFAULT_OPERATION_TARGETS
    ]);
  });
});

describe("surrogate response contracts", () => {
  it("fits the four defined structural responses and excludes damper energy", () => {
    expect(DEFAULT_SURROGATE_TARGET_METRIC_IDS).toEqual([
      "metric_beam_end_ux_peak",
      "metric_tower_base_shear",
      "metric_tower_base_moment",
      "metric_beam_end_ux_cumulative"
    ]);
    expect(DEFAULT_SURROGATE_TARGET_METRIC_IDS.some(id => id.endsWith("_energy"))).toBe(false);
  });

  it("filters undefined damper energy from the selectable fitting responses", () => {
    const metrics: ResultExtractionMetricConfig[] = [
      {
        id: "metric_beam_end_ux_cumulative",
        name: "梁端累计位移",
        objectType: "NODE",
        objectId: "107",
        component: "UX",
        responseType: "DISPLACEMENT",
        statistic: "CUMULATIVE",
        enabled: true,
        autoGenerated: false,
        sourceDescription: "运营累计位移"
      },
      {
        id: "ND01_energy",
        name: "阻尼器耗能",
        objectType: "DAMPER",
        objectId: "USER300:9301",
        component: "LOCAL_AXIAL",
        responseType: "ENERGY",
        statistic: "CUMULATIVE",
        enabled: true,
        autoGenerated: true,
        sourceDescription: "尚未定义"
      }
    ];

    expect(getSurrogateResponseMetricOptions(metrics).map(metric => metric.id)).toEqual([
      "metric_beam_end_ux_cumulative"
    ]);
  });
});
